var questions = [
    "You are almost never late for your appointments",
    "You like to be engaged in an active and fast-paced job",
    "You enjoy having a wide circle of acquaintances",
    "You feel involved when watching TV soaps",
    "You are usually the first to react to a sudden event, such as the telephone ringing or unexpected question",
    "You are more interested in a general idea than in the details of its realization",
    "You tend to be unbiased even if this might endanger your good relations with people",
    "Strict observance of the established rules is likely to prevent a good outcome",
    "It's difficult to get you excited",
    "It is in your nature to assume responsibility",
    "You often think about humankind and its destiny",
    "You believe the best decision is one that can be easily changed",
    "Objective criticism is always useful in any activity",
    "You prefer to act immediately rather than speculate about various options",
    "You trust reason rather than feelings",
    "You are inclined to rely more on improvisation than on prior planning",
    "You spend your leisure time actively socializing with a group of people, attending parties, shopping, etc.",
    "You usually plan your actions in advance",
    "Your actions are frequently influenced by emotions",
    "You are a person somewhat reserved and distant in communication",
    "You know how to put every minute of your time to good purpose",
    "You readily help people while asking nothing in return",
    "You often contemplate the complexity of life",
    "After prolonged socializing you feel you need to get away and be alone",
    "You often do jobs in a hurry",
    "You easily see the general principle behind specific occurrences",
    "You frequently and easily express your feelings and emotions",
    "You find it difficult to speak loudly",
    "You get bored if you have to read theoretical books",
    "You tend to sympathize with other people",
    "You value justice higher than mercy",
    "You rapidly get involved in the social life of a new workplace",
    "The more people with whom you speak, the better you feel",
    "You tend to rely on your experience rather than on theoretical alternatives",
    "As a rule, you proceed only when you have a clear and detailed plan",
    "You easily empathize with the concerns of other people",
    "You often prefer to read a book than go to a party",
    "You enjoy being at the center of events in which other people are directly involved",
    "You are more inclined to experiment than to follow familiar approaches",
    "You avoid being bound by obligations",
    "You are strongly touched by stories about people's troubles",
    "Deadlines seem to you to be of relative, rather than absolute, importance",
    "You prefer to isolate yourself from outside noises",
    "It's essential for you to try things with your own hands",
    "You think that almost everything can be analyzed",
    "For you, no surprises is better than surprises - bad or good ones",
    "You take pleasure in putting things in order",
    "You feel at ease in a crowd",
    "You have good control over your desires and temptations",
    "You easily understand new theoretical principles",
    "The process of searching for a solution is more important to you than the solution itself",
    "You usually place yourself nearer to the side than in the center of a room",
    "When solving a problem you would rather follow a familiar approach than seek a new one",
    "You try to stand firmly by your principles",
    "A thirst for adventure is close to your heart",
    "You prefer meeting in small groups over interaction with lots of people",
    "When considering a situation you pay more attention to the current situation and less to a possible sequence of events",
    "When solving a problem you consider the rational approach to be the best",
    "You find it difficult to talk about your feelings",
    "You often spend time thinking of how things could be improved",
    "Your decisions are based more on the feelings of a moment than on the thorough planning",
    "You feel more comfortable sticking to conventional ways",
    "You are easily affected by strong emotions",
    "You are always looking for opportunities",
    "Your desk, workbench, etc. is usually neat and orderly",
    "As a rule, current preoccupations worry you more than your future plans",
    "You get pleasure from solitary walks",
    "It is easy for you to communicate in social situations",
    "You are consistent in your habits",
    "You willingly involve yourself in matters which engage your sympathies",
    "You easily perceive various ways in which events could develop"
]

// drop questions collection
db.questions.drop()
// pre-populate questions collection
function insert(question) {
    db.questions.insert({
        text: question,
        answer: false
    })
}

questions.forEach(insert)